### ISSUE TITLE
Spotcast link is wrong

### ISSUE THREAD

**Issue by JGNi** [ChrisK91/sonos-playlist-card#1]
Your link to https://github.com/fondberg/spotcast is pointing to a 404 URL.

**Comment by ChrisK91** [comment]
Yes, I accidentally messed up the markdown link formatting. Thanks for the info! It is fixed in https://github.com/ChrisK91/sonos-playlist-card/commit/e3dd0805fcef032792e6e1421e732afba84c3bbd
